//
//  MJINGESignature
//  M1Core
//
//  Created by Generated by Java on 2014-04-16 15:28.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import <CMPLib/CMPObject.h>




@interface MJINGESignature : CMPObject
{
}

@property(nonatomic, copy)NSString        *fieldName;
@property(nonatomic, copy)NSString        *fieldValue;
@property(nonatomic, copy)NSString        *version;
@property(nonatomic, copy)NSString        *recordID;
@property(nonatomic, copy)NSString        *picData;
@property(nonatomic, copy)NSString        *height;
@property(nonatomic, copy)NSString        *width;
@property(nonatomic, copy)NSString        *summaryID;
@property(nonatomic, copy)NSString        *currentOrgID;
@property(nonatomic, copy)NSString        *currentOrgName;

@end
