//
//  MAttachmentBase
//  M1Core
//
//  Created by Generated by Java on 2014-04-16 15:28.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import "MAttachmentBase.h"

@implementation MAttachmentBase
@synthesize  identifier;
@synthesize  name;
@synthesize  size;
@synthesize  createDate;
@synthesize  modifyTime;
@synthesize  reference;
@synthesize  subReference;
@synthesize  category;
@synthesize  mimeType;
@synthesize  verifyCode;


- (void)dealloc
{
    [name release];
    [createDate release];
    [modifyTime release];
    [mimeType release];
    [verifyCode release];

    [super dealloc];
}
@end
