//
//  MAttachment
//  M1Core
//
//  Created by Generated by Java on 2014-04-16 15:28.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import "MAttachment.h"

@implementation MAttachment
@synthesize  attID;
@synthesize  suffix;


- (void)dealloc
{
    [suffix release];

    [super dealloc];
}
@end
