//
//  MAttachmentBase
//  M1Core
//
//  Created by Generated by Java on 2014-04-16 15:28.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import "CMPObject.h"




@interface MAttachmentBase : CMPObject
{
    long long        identifier;
    NSString        *name;
    long long        size;
    NSString        *createDate;
    NSString        *modifyTime;
    long long        reference;
    long long        subReference;
    NSInteger        category;
    NSString        *mimeType;
    NSString        *verifyCode;

}
@property(nonatomic, assign)long long        identifier;
@property(nonatomic, copy)NSString        *name;
@property(nonatomic, assign)long long        size;
@property(nonatomic, copy)NSString        *createDate;
@property(nonatomic, copy)NSString        *modifyTime;
@property(nonatomic, assign)long long        reference;
@property(nonatomic, assign)long long        subReference;
@property(nonatomic, assign)NSInteger        category;
@property(nonatomic, copy)NSString        *mimeType;
@property(nonatomic, copy)NSString        *verifyCode;

@end
