//
//  MAttachment
//  M1Core
//
//  Created by Generated by Java on 2014-04-16 15:28.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import "MAttachmentBase.h"




@interface MAttachment : MAttachmentBase
{
    long long        attID;
    NSString        *suffix;

}
@property(nonatomic, assign)long long        attID;
@property(nonatomic, copy)NSString        *suffix;

@end
