//
//  MMemberIcon
//  M1Core
//
//  Created by Generated by Java on 2016-05-19 15:33.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import "CMPObject.h"




@interface MMemberIcon : CMPObject<NSCoding>
{
    NSString        *iconPath;
    long long        size;
    NSString        *lastModifyDate;
    NSInteger        iconType;
    NSString        *rahmenColor;

}
@property(nonatomic, copy)NSString        *iconPath;
@property(nonatomic, assign)long long        size;
@property(nonatomic, copy)NSString        *lastModifyDate;
@property(nonatomic, assign)NSInteger        iconType;
@property(nonatomic, copy)NSString        *rahmenColor;

@end
